### ISSUE TITLE
Error during laytr giabTR

### ISSUE THREAD

**Issue by raphaelbetschart** [ACEnglish/laytr#3]
Hi,

I'm trying to create an HTML report with `laytr giabTR`. I'm using the following commands:
```
laytr giabTR \
-r HG002/refine.regions.txt \
-b catalogue.bed \
-t adotto_TRregions_v1.2.bed \
-s adotto_TRv1.1_4mers.som \
-m adotto_TRv1.1_4mers.map \
-o HG002_report.html
```

The command runs fine until I get to the SOM step:
```
2024-10-25 11:29:25,728 [INFO] Loading data
2024-10-25 11:29:48,701 [INFO] Subsets report
2024-10-25 11:29:48,838 [INFO] RECM report
2024-10-25 11:29:49,047 [INFO] Entropy report
2024-10-25 11:29:49,487 [INFO] Sizebin report
2024-10-25 11:29:49,726 [INFO] Gene report
2024-10-25 11:29:49,820 [INFO] Interspersed report
2024-10-25 11:29:49,870 [INFO] Complexity report
2024-10-25 11:29:49,942 [INFO] Motif report
2024-10-25 11:29:49,943 [WARNING] /usr/local/lib/python3.10/dist-packages/laytr/giabTR_report.py:271: FutureWarning:The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
2024-10-25 11:29:50,043 [INFO] HomPct report
2024-10-25 11:29:50,840 [INFO] SOMs
Traceback (most recent call last):
  File "/usr/local/bin/laytr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/laytr/__main__.py", line 55, in main
    TOOLS[args.cmd](args.options)
  File "/usr/local/lib/python3.10/dist-packages/laytr/giabTR_report.py", line 414, in giabTRreport_main
    som_1, som_2, som_3, som_4, som_5, som_6 = make_som_report(data, joblib.load(args.som))
  File "/usr/local/lib/python3.10/dist-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.10/dist-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.10/pickle.py", line 1538, in load_stack_global
    self.append(self.find_class(module, name))
  File "/usr/lib/python3.10/pickle.py", line 1582, in find_class
    return _getattribute(sys.modules[module], name)[0]
  File "/usr/lib/python3.10/pickle.py", line 331, in _getattribute
    raise AttributeError("Can't get attribute {!r} on {!r}"
AttributeError: Can't get attribute 'asymptotic_decay' on <module 'minisom' from '/usr/local/lib/python3.10/dist-packages/minisom.py'>
```
Do you have in idea what could be the issue? I've tried to install `laytr` with both the instructions and the provided dockerfile.
Best,
Raphael

**Comment by ACEnglish** [comment]
This looks like minisom has changed their code such that the function `asymptotic_decay` has become `_asymptotic_decay`, which breaks the pickled object provided in `adotto_TRv1.1_4mers.som`. Furthermore, laytr has an install requirement of `minisom >= 2.3`, which allowed this new version in. 

I have just pushed a change so that laytr now pins to `minisom == 2.3.1`, which should be compatible with the adotto som.

**Comment by raphaelbetschart** [comment]
Perfect, thanks for the quick fix!
Have a nice weekend,
Raphael
